#include "virtuoso/drums/FluffyAudioJazzDrumsBrushesMapping.h"

namespace virtuoso::drums {

QVector<FluffyAudioBrushesNote> fluffyAudioJazzDrumsBrushesNotes() {
    // Keep this list stable; it’s referenced by future improvisation/driver logic.
    // If the vendor updates mappings, add a new "mapping version" rather than editing in place.
    return {
        {24, "C0",  "HiHat/Hits - Almost Closed - Bell", 0},
        {25, "C#0", "HiHat/Hits - Almost Closed - Rimshot", 0},
        {26, "D0",  "HiHat/Hits - Open - Bell", 0},
        {27, "D#0", "Crash/Effects - Scratching", 4000},
        {28, "E0",  "F. Tom/Effects - Rattle", 2000},
        {29, "F0",  "N/A", 0},
        {30, "F#0", "N/A", 0},
        {31, "G0",  "Kick/Loose - Normal", 0},
        {32, "G#0", "HiHat/Pedal - Half Open - Close", 0},
        {33, "A0",  "Kick/Loose - Sforzando", 0},
        {34, "A#0", "HiHat/Pedal - Open Control - Closing", 0},
        {35, "B0",  "Kick/Tight - Normal", 0},
        {36, "C1",  "Kick/Tight - Sforzando", 0},
        {37, "C#1", "Snare/Hits - Rimshot Right - Brush + Stick (strong hits)", 0},
        {38, "D1",  "Snare/Hits - Right Hand", 0},
        {39, "D#1", "Snare/Hits - Rimshot - Strong Hits", 0},
        {40, "E1",  "Snare/Hits - Rimshot - Brush on Edge", 0},
        {41, "F1",  "F. Tom/Rimshot - Right Hand", 0},
        {42, "F#1", "HiHat/Hits - Closed - Edge", 0},
        {43, "G1",  "F. Tom/Hits - Right Hand", 0},
        {44, "G#1", "HiHat/Pedal - Half Open - Close", 0},
        {45, "A1",  "Tom/Rimshot - Right Hand", 0},
        {46, "A#1", "HiHat/Hits - Almost Closed - Edge", 0},
        {47, "B1",  "Tom/Hits - Right Hand", 0},
        {48, "C2",  "Tom/Rimshot - Left Hand", 0},
        {49, "C#2", "Crash/Hits - Right Hand", 0},
        {50, "D2",  "Tom/Rimshot - Left Hand", 0},
        {51, "D#2", "Ride/Hits - Border", 0},
        {52, "E2",  "Ride/Effects - Swish 2", 4000},
        {53, "F2",  "Ride/Hits - Bell", 0},
        {54, "F#2", "Rude/Effects - Swish", 3000},
        {55, "G2",  "Snare/Colors - RattleSnake 2 - Looped (full sample ~3000ms)", 0},
        {56, "G#2", "Sizzle C./Hits - Bell", 0},
        {57, "A2",  "Crash/Hits - Effects Swish", 0},
        {58, "A#2", "Ride/Effects - Rattle - Looped", 4000},
        {59, "B2",  "Sizzle C./Hits - Border", 0},
        {60, "C3",  "N/A", 0},
        {61, "C#3", "N/A", 0},
        {62, "D3",  "Snare/Colors - RattleSnake 1", 3000},
        {63, "D#3", "Snare/Colors - RattleSnake 2 - Looped (full sample ~4000ms)", 0},
        {64, "E3",  "Snare/Hits - Brushing", 4000},
        {65, "F3",  "Snare/Hits - Brushing Fast - Mezzoforte", 2000},
        {66, "F#3", "Snare/Brushing - Speed Control - Circle Two Hands - Looping (full sample ~6000ms)", 6000},
        {67, "G3",  "Snare/Brushing - Speed Control - Circle Right Hand - Looping (full sample ~4000ms)", 4000},
        {68, "G#3", "Snare/Brushing - Speed Control - Short Right Hand", 1000},
        {69, "A3",  "Snare/Brushing - Speed Control - Medium Right Hand", 0},
        {70, "A#3", "Snare/Brushing - Speed Control - Long Right Hand", 1000},
        {71, "B3",  "Kick/Loose - Normal", 0},
        {72, "C4",  "Kick/Loose - Sforzando", 0},
        {73, "C#4", "Snare/Hits - Right Hand - Stopped", 0},
        {74, "D4",  "Snare/Hits - Left Hand - Stopped", 0},
        {75, "D#4", "Snare/Hits - Rimshot Left - Brush + Stick (strong hits)", 0},
        {76, "E4",  "Snare/Hits - Right Hand", 0},
        {77, "F4",  "Snare/Hits - Rimshot Left - Stick Only (strong hits)", 0},
        {78, "F#4", "HiHat/Hits - Closed - Edge", 0},
        {79, "G4",  "F. Tom/Rimshot - Left Hand", 0},
        {80, "G#4", "HiHat/Pedal - Almost Close - Close", 0},
        {81, "A4",  "F. Tom/Hits - Left Hand", 0},
        {82, "A#4", "HiHat/Hits - Half Open - Edge", 0},
        {83, "B4",  "Tom/Rimshot - Left Hand", 0},
        {84, "C5",  "Tom/Hits - Left Hand", 0},
        {85, "C#5", "HiHat/Pedal - Half Open - Stroke", 0},
        {86, "D5",  "F. Tom/Effects - Rattle", 1000},
        {87, "D#5", "Ride/Hits - Border", 0},
        {88, "E5",  "Ride/Effects - Sidehit", 0},
        {89, "F5",  "Ride/Hits - Bell", 0},
        // NOTE: user-provided mapping included a duplicate "D5" entry for Ride Swish 2.
        // We keep it as an alias (same MIDI = 74) so the original mapping is preserved.
        {86, "D5",  "Ride/Effects - Swish 2 (alias as provided; noteName duplicates)", 4000},
        {91, "G5",  "Sizzle C./Hits - Border", 0},
        {92, "G#5", "Sizzle C./Hits - Bell", 0},
        {93, "A5",  "Crash/Hits - Right Hand", 0},
        {94, "A#5", "HiHat/Pedal - Half Open - Loud Stroke", 0},
        {95, "B5",  "HiHat/Hits - Open Control - Edge", 0},
    };
}

} // namespace virtuoso::drums

